site_name:           Brim.jl
repo_url:            https://github.com/PoisotLab/Brim.jl
site_description:    Optimization and significance testing of bipartite modularity.
site_author:         Timothée Poisot
theme:               yeti
markdown_extensions: [tables, fenced_code]
pages:
  - ['index.md', 'User guide']
  - ['api.md', 'Developer guide', 'API reference']
  - ['contr.md', 'Developer guide', 'Contribution guide']
