site_name:           Brim.jl
site_description:    Optimization and significance testing of bipartite modularity.
repo_url:            https://github.com/PoisotLab/Brim.jl
site_author:         Timothée Poisot
markdown_extensions:
  - tables
  - fenced_code

pages:
  - Introduction: index.md
  - User manual:
    - Initial partition: intro/partitions.md
    - Optimization and measure: intro/optimize.md
    - Network roles: intro/roles.md
    - Permutations: intro/permut.md
    - Visualizations: intro/visualization.md
  - Examples:
    - Modularity of a large network: examples/kato.md
    - Permutations: examples/inouyepike.md
  - API: api.md
  - How to contribute: contr.md
