site_name:           Brim.jl
repo_url:            https://github.com/PoisotLab/Brim.jl
site_description:    Optimization and significance testing of bipartite modularity.
site_author:         Timothée Poisot
theme:               readthedocs
markdown_extensions: [tables, fenced_code]
pages:
  - ['index.md', 'User guide']
  - ['intro/partitions.md', 'User guide', 'Initial partitions']
  - ['intro/optimize.md', 'User guide', 'Optimization and measure']
  - ['intro/roles.md', 'User guide', 'Modularity roles']
  - ['api.md', 'Developer guide', 'API reference']
  - ['contr.md', 'Developer guide', 'Contribution guide']
